### ISSUE TITLE
Poprawne wyswietlanie pol typu status

### ISSUE THREAD

**Issue by frqdea** [wutee/propsy-backend#12]
Wyswietlanie statusow np. RestaurantWorker.workingStatus == 'pracuje', 'zwolniony', 'urlop' zamiast 0, 1, 2

**Comment by owlcode** [comment]
1.  Nie będziemy mieli czegoś takiego jak status pracownika
2. Status zamówienia będzie załatwiony przez Enum z Jhipstera
```
enum OrderStatus {
    NEW, PAYMENT, CONFIRMED, IN_PROGRESS, TO_PICK_UP, IN_DELIVERY, DELIVERED
}
```

Zamykam 🏆
