### ISSUE TITLE
Bidirectional mapping

### ISSUE THREAD

**Issue by frqdea** [wutee/propsy-backend#14]
restaurant/menu
food/menu
order/food
etc

**Comment by owlcode** [comment]
Możesz rozwinąć myśl? @frqdea @kok00n

**Comment by frqdea** [comment]
jhipster nie wspomaga dwukierunkowych relacji, jesli nie jest to wiele do wielu. aktualnie np. nie da sie sprawdzic w obiekcie menu do jakiej restauracji nalezy, trzeba robic selecta po restauracjach. na froncie jest to chyba rozwiazane wiec mozna to zamknac
