### ISSUE TITLE
Rozszerzenie API o wyszukiwanie po wartosciach pól

### ISSUE THREAD

**Issue by frqdea** [wutee/propsy-backend#9]
Wyszukiwanie elementow po wartosciach kolumn natywnych badz wartosciach id powiazanych tabeli. np.: 
Order dla customer.id == 1;
Order dla status == 0

**Comment by owlcode** [comment]
Linkuję PR z przykładowym rozwiązaniem. Zachęcam do testowania. Jeżeli ktokolwiek będzie potrzebował podobnych rzeczy, niech działa w ten sam sposób, wg mnie działa 👍
